language: generic
services:
  - docker

before_install:
  - docker build -t willykind/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true willykind/react-test npm test

after_success:
  - docker build -t willykind/multi-client ./client
  - docker build -t willykind/multi-nginx ./nginx
  - docker build -t willykind/multi-server ./server
  - docker build -t willykind/multi-worker ./worker

  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take all images and push them to Docker Hub
  - docker push willykind/multi-client
  - docker push willykind/multi-nginx
  - docker push willykind/multi-server
  - docker push willykind/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-261751828690"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
